In [1]:
import pandas as pd
import numpy as np

In [2]:
customers = 1000000

dates = pd.date_range("2024-01-01","2024-12-31")

purchase_dates = np.random.choice(dates,customers)

tenure = np.random.choice(
    [1,2,3,4],
    size=customers,
    p=[0.2,0.3,0.4,0.1]
)

policy = pd.DataFrame({
"Customer_ID": range(1,customers+1),
"Vehicle_ID": range(1000001,1000001+customers),
"Vehicle_Value":100000,
"Policy_Tenure":tenure,
"Policy_Purchase_Date":purchase_dates
})

policy["Premium"]=policy["Policy_Tenure"]*100
policy["Policy_Start_Date"]=policy["Policy_Purchase_Date"]+pd.Timedelta(days=365)
policy["Policy_End_Date"]=policy["Policy_Start_Date"]+pd.to_timedelta(policy["Policy_Tenure"]*365,unit="D")

policy.to_csv("policy_sales_data.csv",index=False)

policy.head()

,Customer_ID,Vehicle_ID,Vehicle_Value,Policy_Tenure,Policy_Purchase_Date,Premium,Policy_Start_Date,Policy_End_Date
0,1,1000001,100000,3,2024-12-04,300,2025-12-04,2028-12-03
1,2,1000002,100000,3,2024-09-01,300,2025-09-01,2028-08-31
2,3,1000003,100000,3,2024-12-14,300,2025-12-14,2028-12-13
3,4,1000004,100000,3,2024-05-31,300,2025-05-31,2028-05-30
4,5,1000005,100000,3,2024-05-21,300,2025-05-21,2028-05-20

In [3]:
policy = pd.read_csv("policy_sales_data.csv")

policy["Policy_Purchase_Date"]=pd.to_datetime(policy["Policy_Purchase_Date"])
policy["Policy_Start_Date"]=pd.to_datetime(policy["Policy_Start_Date"])

claim_days=[7,14,21,28]

eligible = policy[policy["Policy_Purchase_Date"].dt.day.isin(claim_days)]

claims_2025 = eligible.sample(frac=0.30)

claims_2025["Claim_Date"]=claims_2025["Policy_Start_Date"]
claims_2025["Claim_Type"]=1
claims_2025["Claim_Amount"]=10000

four_year = policy[policy["Policy_Tenure"]==4]

claims_2026 = four_year.sample(frac=0.10)

dates = pd.date_range("2026-01-01","2026-02-28")

claims_2026["Claim_Date"]=np.random.choice(dates,len(claims_2026))
claims_2026["Claim_Type"]=2
claims_2026["Claim_Amount"]=10000

claims=pd.concat([claims_2025,claims_2026])

claims["Claim_ID"]=range(1,len(claims)+1)

claims = claims[[
"Claim_ID",
"Customer_ID",
"Vehicle_ID",
"Claim_Amount",
"Claim_Date",
"Claim_Type"
]]

claims.to_csv("claims_data.csv",index=False)

claims.head()

        Claim_ID  Customer_ID  Vehicle_ID  Claim_Amount Claim_Date  Claim_Type
979940         1       979941     1979941         10000 2025-06-28           1
782452         2       782453     1782453         10000 2025-04-28           1
22328          3        22329     1022329         10000 2025-07-07           1
49888          4        49889     1049889         10000 2025-11-14           1
231284         5       231285     1231285         10000 2025-06-28           1